config/routes.rb
Playlist::Application.routes.draw do
  get "results/index"

  root 'results#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  def index
    @songs = Nashville::Music.search(song: params[:search], limit: 10)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Playlist</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class="container">
		<%= yield %>
	</div>

	<script type='text/javascript'>var _merchantSettings=_merchantSettings || [];_merchantSettings.push(['AT', '11l4Dk']);(function(){var autolink=document.createElement('script');autolink.type='text/javascript';autolink.async=true; autolink.src= ('https:' == document.location.protocol) ? 'https://autolinkmaker.itunes.apple.com/js/itunes_autolinkmaker.js' : 'http://autolinkmaker.itunes.apple.com/js/itunes_autolinkmaker.js';var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(autolink, s);})();
	</script>
</body>
</html>

app/views/results/index.html.erb
<nav class="navbar navbar-default" role="navigation">
	<div class="container-fluid">
		<div class="navbar-header">
			<%= link_to "Playlist", root_url, class: "navbar-brand" %>
			<%= form_tag results_index_path, :method => 'get', role: "search", class: "navbar-form navbar-left" do %>
				<div class="form-group">
					<%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search a Song" %>
				</div>
				<%= submit_tag "Search", :name => nil, class: "btn btn-default" %>
				<%= link_to "Reset", root_url, class: "btn btn-default" %>
			<% end %>
		</div>
	</div>
</nav>

<table class="table table-bordered">
	<thead>
		<tr>
			<th>Artwork</th>
			<th>Artist</th>
			<th>Track</th>
			<th>Album</th>
			<th>Price</th>
		</tr>
	</thead>
	<tbody>
		<% @songs.each do |song| %>
			<tr>
				<td><%= image_tag song.artworkUrl60 %></td>
				<td><h4><%= song.artistName %></h4></td>
				<td><h4><%= song.trackName %></h4></td>
				<td><h4><%= song.collectionName %></h4></td>
				<td>
					<%= link_to (number_to_currency song.trackPrice), song.trackViewUrl, class: "label label-success" %>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>